### ISSUE TITLE
Support normal YAML syntax for tasks

### ISSUE THREAD

**Issue by ypid** [MicahElliott/Rocannon#4]
First of all, thanks very much for the plugin, great stuff :+1: 

The "inline" format advocated by Ansible in the paste is now basically deprecated (ref: https://www.ansible.com/blog/ansible-best-practices-essentials 3. Use Native YAML Syntax). Official docs should also be mostly up-to-date by now.

It seems that Rocannon does not support the regular YAML syntax for tasks omni-completion?

Example:

```YAML
- name: configure telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf
```
